name: CI

on:
- push
- pull_request
- workflow_dispatch

jobs:
  host:
    name: ${{ matrix.os }} ${{ matrix.ruby }} ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        ruby:
          - "head"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: "${{ startsWith(matrix.ruby, 'jruby') && 'ragel' || '' }}"
          brew: "${{ startsWith(matrix.ruby, 'jruby') && 'ragel' || '' }}"

      - run: |
          bundle config --without benchmark
          bundle install

      - run: |
          ruby -v -rmkmf -e "p have_devel?" || cd .
          type mkmf.log

      - run: rake compile ${{ matrix.env }}

      - run: rake test JSON_COMPACT=1 ${{ matrix.env }}

      - run: rake build

      - run: gem install pkg/*.gem
        if: ${{ matrix.ruby != '3.2' }}
